import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";
import Head from "next/head";
import Image from "next/image";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (user)
    return (
      <div className="flex w-full flex-row">
        <Image
          width={14}
          height={14}
          className="h-14 w-14 rounded-full"
          src={user.profileImageUrl}
          alt="Profile Image"
        />
        <input
          className="ml-4 grow bg-transparent p-4 outline-none placeholder:text-slate-100"
          placeholder="Type you're emojis here!"
        />
      </div>
    );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className="border-b border-slate-400 p-8" key={post.id}>
      <Image
        width={14}
        height={14}
        className="h-14 w-14 rounded-full"
        src={author.profileImageUrl}
        alt="Profile Image"
      />
      {post.content}
    </div>
  );
};

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if (isLoading) return <div>Loading...</div>;
  // if (!data) return <div>No data in the server...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center ">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
